### ISSUE TITLE
Can't open editor

### ISSUE THREAD

**Issue by austin-hwang** [AnthonyMichaelTDM/rust-DRG-Save-Editor#1]
Seems like there's an issue when attempting to run the program. Not familiar with Rust so not sure what the problem is here
![image](https://user-images.githubusercontent.com/13093521/193953619-15195abb-ee83-4b01-9cb4-db5e01cfe903.png)

**Comment by AnthonyMichaelTDM** [comment]
I'll look into that, but the editor is not working currently, beyond a gui frontend (backend is missing rn)

**Comment by AnthonyMichaelTDM** [comment]
The panic is caused because the compiler is hitting one of my todo!() statements, if you want to run the gui you can remove those from the app.rs file, but again, the gui isn't hooked up to any backend yet

**Comment by AnthonyMichaelTDM** [comment]
I'll update the readme when I get back to my computer in ~10mins

**Comment by AnthonyMichaelTDM** [comment]
I'm going to mark this as resolved, feel free to re-open if you have more questions
